/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Progress = IDL.Record({
  'levelId' : IDL.Text,
  'bestMoveCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllProgress' : IDL.Func([], [IDL.Vec(Progress)], ['query']),
  'getBestMoveCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getHighestLevelReached' : IDL.Func([], [IDL.Nat], ['query']),
  'markLevelCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'resetProgress' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Progress = IDL.Record({
    'levelId' : IDL.Text,
    'bestMoveCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllProgress' : IDL.Func([], [IDL.Vec(Progress)], ['query']),
    'getBestMoveCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getHighestLevelReached' : IDL.Func([], [IDL.Nat], ['query']),
    'markLevelCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'resetProgress' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };